-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Object.Package exposing (..)

import API.InputObject
import API.Interface
import API.Object
import API.Scalar
import API.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) API.Object.Package
selection constructor =
    Object.selection constructor


builds : SelectionSet decodesTo API.Object.Build -> Field (List decodesTo) API.Object.Package
builds object =
    Object.selectionField "builds" [] object (identity >> Decode.list)


insertedAt : Field API.Scalar.DateTime API.Object.Package
insertedAt =
    Object.fieldDecoder "insertedAt" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map API.Scalar.DateTime)


name : Field String API.Object.Package
name =
    Object.fieldDecoder "name" [] Decode.string


source : Field String API.Object.Package
source =
    Object.fieldDecoder "source" [] Decode.string


updatedAt : Field API.Scalar.DateTime API.Object.Package
updatedAt =
    Object.fieldDecoder "updatedAt" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map API.Scalar.DateTime)


versions : SelectionSet decodesTo API.Object.Version -> Field (List decodesTo) API.Object.Package
versions object =
    Object.selectionField "versions" [] object (identity >> Decode.list)
