-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Object exposing (..)


type Build
    = Build


type Package
    = Package


type Version
    = Version
