-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module API.Scalar exposing (..)


type Date
    = Date String


type DateTime
    = DateTime String


type Id
    = Id String


type NaiveDateTime
    = NaiveDateTime String


type Time
    = Time String
